# Generated by Django 5.2.11 on 2026-07-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_eng_part',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_mktg_part',
        ),
        migrations.AddField(
            model_name='product',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot balance at time of import, not live inventory.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='legacy_part_no',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='max_stock_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('tenant', 'parent', 'code'), name='unique_category_code_per_parent'),
        ),
    ]
