# Generated by Django 5.2.11 on 2026-07-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_invoice_status_order_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='oacommercialterms',
            name='commissioning_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oacommercialterms',
            name='commissioning_visits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oacommercialterms',
            name='delivery_basis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='oacommercialterms',
            name='delivery_period_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oacommercialterms',
            name='directors_indemnity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='oacommercialterms',
            name='erection_guidelines',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='oacommercialterms',
            name='gst_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='oacommercialterms',
            name='packing_extra_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='oacommercialterms',
            name='packing_forwarding',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='oacommercialterms',
            name='payment_milestones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='oacommercialterms',
            name='pbg_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='oacommercialterms',
            name='special_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='oacommercialterms',
            name='technical_spec_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oacommercialterms',
            name='commissioning_support',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oacommercialterms',
            name='dispatch_clearance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='oacommercialterms',
            name='drawing_approval',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='oacommercialterms',
            name='freight_charges',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='oacommercialterms',
            name='inspection',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='oacommercialterms',
            name='insurance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='oacommercialterms',
            name='payment_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oacommercialterms',
            name='price_basis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='oacommercialterms',
            name='warranty',
            field=models.TextField(blank=True),
        ),
    ]
