# Generated by Django 5.2.11 on 2026-07-30 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_oacommercialterms_commissioning_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='oa_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('oa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.orderacknowledgement')),
            ],
        ),
    ]
