# Generated by Django 5.2.11 on 2026-07-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationterms',
            name='abg_format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='advance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='commissioning_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='commissioning_support',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='commissioning_visits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='days_after_invoicing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='delivery_basis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='delivery_period_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='directors_indemnity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='dispatch_clearance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='drawing_approval',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='erection_guidelines',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='gst_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='inspection',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='ld_clause',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='packing_extra_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='payment_milestones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='pbg_format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='pbg_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='sd_format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='special_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='technical_spec_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='test_certificate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quotationterms',
            name='freight',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationterms',
            name='insurance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationterms',
            name='packing_forwarding',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationterms',
            name='price_basis',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
