# Generated by Django 5.2.11 on 2026-07-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotationterms_abg_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationterms',
            name='cost_over_run',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='country_origin_material_certs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='force_majeure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='late_delivery_charges',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='ordering_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='po_cancellation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='price_validity',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
